spring.application.name=server
server.port=8081

# Impede que o servidor tente se registrar em si mesmo
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

# No Docker, o 'localhost' dentro do container não alcança outros containers.
# Usamos a variável para que ele saiba seu próprio endereço na rede Docker.
eureka.client.serviceUrl.defaultZone=http://${EUREKA_SERVER_HOST:localhost}:8081/eureka
