server.port=8082
debug=true
# Conecta no Eureka usando o nome do serviço no Docker
eureka.client.serviceUrl.defaultZone=http://${EUREKA_SERVER_HOST:localhost}:8081/eureka

spring.application.name=gateway

spring.cloud.gateway.server.webflux.discovery.locator.enabled=true
spring.cloud.gateway.server.webflux.discovery.locator.lower-case-service-id=true
