server.port=8082
debug=true
eureka.client.serviceUrl.defaultZone=http://localhost:8081/eureka

spring.application.name=gateway

spring.cloud.gateway.server.webflux.discovery.locator.enabled=true
spring.cloud.gateway.server.webflux.discovery.locator.lower-case-service-id=true
