spring.application.name=SMS
twilio.sid=${TWILIO_SID}
twilio.token=${TWILIO_TOKEN}
debug=true
server.port=8085

eureka.client.serviceUrl.defaultZone=http://localhost:8081/eureka


spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest