spring.application.name=email
server.port=8084

# Banco de dados (usando variável para o HOST)
spring.datasource.url=jdbc:postgresql://${SPRING_DATASOURCE_URL_HOST:localhost}:5432/notification
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=update

# RabbitMQ
spring.rabbitmq.host=${SPRING_RABBITMQ_HOST:localhost}
spring.rabbitmq.port=5672
fila.direct=fila.email

# Eureka
eureka.client.serviceUrl.defaultZone=http://${EUREKA_SERVER_HOST:localhost}:8081/eureka

# Variáveis para API de Email (ex: Mailgun, SendGrid)
api.token=${API_TOKEN_EMAIL}
api.domain=${API_DOMAIN}
