spring.application.name=email
server.port=8084

spring.datasource.url=jdbc:postgresql://localhost:5432/ms-email
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

fila.direct=fila.email
eureka.client.serviceUrl.defaultZone=http://localhost:8081/eureka

api.token=mlsn.28f8d4bfa97c4ecce3d43b4edbf69bfeeaab21f20ff55e311148f500df13e2aa